### ISSUE TITLE
Not able to create directory babel (for generated code)  with tangle-all.sh in cygwin

### ISSUE THREAD

**Issue by yubrshen** [thi-ng/babel#3]
I got the following error:

B37747@B37747-11 ~/dev/clojurescript
$ lein new thing-babel bar
Generating fresh literate programming project: bar
generated project dir   : bar
artefact group ID       :
project url             : https://github.com/
project author          : B37747
author url              :
author email            :
author timezone         : 8
license                 : Eclipse Public License
description             : FIXME: write description
path for gen sources    : babel\
project root namespace  : bar

B37747@B37747-11 ~/dev/clojurescript
$ cd bar

B37747@B37747-11 ~/dev/clojurescript/bar
$ ./tangle-all.sh
2 src blocks added to Library of Babel
Cannot read file "/cygdrive/d/yushen/dev/clojurescript/bar/setup.org"
Cannot read file "/cygdrive/d/yushen/dev/clojurescript/bar/setup.org"
(No changes need to be saved)
Opening output file: no such file or directory, /cygdrive/d/yushen/dev/clojurescript/bar/babel\project.clj

It's with version 0.3.1. 

My environment is cygwin with Windows 7. 

I suspect that the problem is related to the combination of Winodws and Cygwin. 
I can overcome the problem by manually doing the tangling in emacs buffer with README.org.

**Comment by postspectacular** [comment]
Hiya, looking at this:

> Opening output file: no such file or directory, /cygdrive/d/yushen/dev/clojurescript/bar/babel\project.clj

..it seems I shouldn't use the system file seperator and always use "/" in tangle target paths. I've just deployed 0.3.2 which addresses this (and #2 as well). Please let me know if that works for you...

**Comment by yubrshen** [comment]
Yes, this issue is fixed.

With the work-around to create the template, I was able to execute and get
the all passed:

B37747@B37747-11 ~/dev/clojure
$ cd bar

B37747@B37747-11 ~/dev/clojure/bar
$ ls
README.org  src  tangle.sh  tangle-all.sh  test

B37747@B37747-11 ~/dev/clojure/bar
$ ./tangle-all.sh
2 src blocks added to Library of Babel
(No changes need to be saved)
Wrote /cygdrive/d/yushen/dev/clojure/bar/babel/project.clj
Wrote /cygdrive/d/yushen/dev/clojure/bar/babel/src/bar/version.cljc
Wrote /cygdrive/d/yushen/dev/clojure/bar/babel/index.html
Tangled 3 code blocks from README.org
(No changes need to be saved)
executing Emacs-Lisp code block (lob-bar-greetings)...

(msg (quote "hello world"))

"(defn show-greetings
   [] (println \"hello world\"))"
Wrote /cygdrive/d/yushen/dev/clojure/bar/babel/src/bar/core.cljc
Tangled 1 code block from core.org
(No changes need to be saved)
Tangled 0 code blocks from libraryofbabel.org
(No changes need to be saved)
Tangled 0 code blocks from setup.org
(No changes need to be saved)
Wrote /cygdrive/d/yushen/dev/clojure/bar/babel/test/bar/test/core.cljc
Tangled 1 code block from core.org

B37747@B37747-11 ~/dev/clojure/bar
$ cd babel/

B37747@B37747-11 ~/dev/clojure/bar/babel
$ lein test bar.test.core

lein test bar.test.core

lein test :only bar.test.core/epic-fail

FAIL in (epic-fail) (core.cljc:9)
FIXME
expected: (= 3 (+ 1 1))
  actual: (not (= 3 2))

Ran 1 tests containing 1 assertions.
1 failures, 0 errors.
Tests failed.

B37747@B37747-11 ~/dev/clojure/bar/babel
$

--
Thanks,

Yu

**Comment by postspectacular** [comment]
Oki, thanks @yubrshen!
